---
apiVersion: v1
kind: Pod
metadata:
  namespace: bouncer-example
  name: etherpad
  labels:
    app: etherpad
spec:
  containers:
    - name: etherpad
      image: docker.io/etherpad/etherpad:1.8.13
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 9001
