---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bouncer
commonLabels:
  app: bouncer-admission-controller
resources:
  - cert-bouncer.yaml
  - deploy.yaml
  - svc.yaml
  - bouncer-validating-webhook.yaml
  - netpol.yaml
