---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-authority
  namespace: cert-manager
spec:
  secretName: neonmei-certificate-authority
  # 365d
  duration: 8760h
  isCA: true
  commonName: neonmei
  subject:
    organizations:
      - Shenzhou
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: issuer-selfsigned
    kind: ClusterIssuer
